spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer #need this to received data as json

#      config error handler serializationException
      properties:
          spring.json.trusted.packages: "*"

#      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    #      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer #need this to sent data as json
#      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

